### ISSUE TITLE
Potential EULA violation

### ISSUE THREAD

**Issue by fontpolice** [jfmdev/TuringFonts#1]
Dear jfmdev,

It has come to our attention through [FontFinder](http://www.fontfinder.io) that your hosting of arial_atbash.woff in this _public_ repository could be a potential violation of the End User License Agreement (EULA) between yourself and the respective foundry.

We recommend that you [remove](https://github.com/blog/1545-deleting-files-on-github) the files to avoid further action.

Sincerely,
The Font Police

**Comment by jfmdev** [comment]
Dear Font Police,

Thanks for your notification. The file "arial_atbash.woff" as been removed from the repository.

Best regards,
JFMDev

**Comment by fontpolice** [comment]
Thank you for your cooperation.
